version: 0.2

env:
  parameter-store:
    SNYK_TOKEN: "snyk-api-token"
    SONAR_KEY: "/cfgc/cicd/sonar-key"
    SLACK_CHANNEL: "/cfgc/global/slack-web-hook"
    IdamReleaseNumber: "/cfcp/idam/ManagementReleaseNumber"
  
  phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
      - unzip sonar-scanner-cli-4.2.0.1873-linux.zip
      - mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
      - ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
      - npm install -g prettier
      - npm install -g snyk
      - npm install --save-dev jest babel-jest @babel/preset-env
      - pip install black
      - pip install marshmallow==2.20.1
      - pip install -r development.txt

  build:
    commands:
      - echo Running CI tests...
      - python3 run_ci.py
