version: '3'

services:
  idam:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    restart: always
    ports:
      - "1060:8000"
    environment:
      WORKERS: 1
      LOG_FOLDER: /var/log/idam
      ACCESS_LOG: '-'
      ERROR_LOG: '-'
      LOG_LEVEL: 'DEBUG'
      COOKIE_DOMAINS: 'localhost:1060'
      SESSION_COOKIE_SECURE: 'False'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SESSION_TOKEN: '${AWS_SESSION_TOKEN}'
      JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
      USER_POOL_ID: '${USER_POOL_ID}'
      CLIENT_ID: '${CLIENT_ID}'
      CLIENT_SECRET: '${CLIENT_SECRET}'
      PLATFORM_CLIENT_ID: '${PLATFORM_CLIENT_ID}'
      PLATFORM_CLIENT_SECRET: '${PLATFORM_CLIENT_SECRET}'
      AWS_REGION_NAME: '${AWS_REGION_NAME}'
      IDAM_UI_BASE_URL: '${IDAM_UI_BASE_URL}'
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:idam@idam_db/idam
      REDIS_URL: redis://idam_cache:6379
      JSON_SORT_KEYS: 'False'
      LOCAL_DEV: 'True'
      PERF_TEST: '${PERF_TEST}'
      APP_VERSION: '0.0.1'
      OPENAPI_VERSION: '3.0.3'
      TITLE: 'IDAM API'
      AWS_AUTH_URL: 'https://idam.auth.eu-west-1.amazoncognito.com'
    volumes:
      - .data/idam/logs:/var/log/idam
      - .:/opt/idam
    depends_on: 
      - idam_db
    networks:
        default:
        internal:

  idam_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: idam
      MYSQL_USER: idam
      MYSQL_PASSWORD: idam
      MYSQL_DATABASE: idam
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:

  idam_cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true


